#!/bin/sh

displayUsage()
{
    echo "---------------------------------------------------------------------------"
    echo "Build container: "
    echo "  docker-cli build"
    echo ""
    echo "Start container: "
    echo "  docker-cli start"
    echo ""
    echo "Stop container: "
    echo "  docker-cli stop"
    echo ""
    echo "Connect to dev container: "
    echo "  docker-cli exec"
    echo "---------------------------------------------------------------------------"
}


start()
{
    docker-compose -f docker/docker-compose.yml up -d
}

stop()
{
    echo "Cleaning inner (Docker In Docker) containers"
    docker exec mattermost-dev docker ps -aq
    docker exec mattermost-dev docker stop $(docker ps -aq)
    docker exec mattermost-dev docker system prune -a -f
    echo "Tearing down"
    docker-compose -f docker/docker-compose.yml down
}

build()
{
    docker-compose -f docker/docker-compose.yml build
}

containerExec()
{
    docker-compose -f docker/docker-compose.yml exec mattermost bash
}

case "$1" in
    build)
        build
    ;;
    start)
        start
    ;;
    stop)
        stop
    ;;
    exec)
        containerExec
    ;;
    *) displayUsage
    ;;
esac